#!/bin/bash
#
# Set the network hostname
#
# Usage:
#
#   recipe 'hostname' '<hostname to set>'

if ! is_installed $*; then
    local host="$2"

    echo "$host" > /etc/hostname
    perl -i.bak -pe 's/^127.0.1.1\s/127.0.1.1\t$host/;' /etc/hosts

    set_installed $*
fi
